name: 'Asana Sync'
description: 'Sync Github PRs to Asana Tasks'
author: 'Sam Macbeth'
inputs:
  ASANA_WORKSPACE_ID:
    required: false
    description: 'Asana workspace ID'
runs:
  using: 'node16'
  main: 'dist/index.js'
