name: "asana sync"
on:
  pull_request_review:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - review_requested

jobs:
  sync:
    runs-on: default
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          ASANA_ACCESS_TOKEN: ${{ secrets.DAX_ASANA_AUTH_TOKEN }}
          ASANA_WORKSPACE_ID: ${{ secrets.ASANA_WORKSPACE_ID }}
          ASANA_PROJECT_ID: "1204969954708911"
