name: "build-test"
on: # rebuild any PRs
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: default
    env:
      NODENV_VERSION: "16.16.0"
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
